"""
Maps MTGish typed operator nodes to human-readable semantic tags.

Tag namespaces:
  t:    trigger   — WHEN the ability fires
  e:    effect    — WHAT the ability does
  c:    counter   — what KIND of counter is involved
  k:    keyword   — keyword ability (static/evasion)
  tgt:  target    — WHO is affected (player)
  perm: perm type — WHAT TYPES of permanents the ability cares about
  r:    replace   — replacement effect type
"""

# ── Trigger map ───────────────────────────────────────────────────────────────

TRIGGER_MAP: dict[str, list[str]] = {
    # ETB / leaving
    "WhenAPermanentEntersTheBattlefield":                               ["t:etb"],
    "WhenAPermanentEntersTheBattlefieldUnderAPlayersControl":           ["t:etb"],
    "WhenAPermanentLeavesTheBattlefield":                               ["t:leaves"],
    "WhenAPermanentDies":                                               ["t:creature_dies"],
    "WhenACreatureOrPlaneswalkerDies":                                  ["t:creature_dies"],
    "WhenAPermanentIsDestroyed":                                        ["t:permanent_destroyed"],
    "WhenAPermanentIsSacrificed":                                       ["t:sacrifice"],
    "WhenAPlayerSacrificesAPermanent":                                  ["t:sacrifice"],
    "WhenAPermanentIsExiled":                                           ["t:exiled"],
    "WhenAPermanentIsTransformed":                                      ["t:transform"],
    "WhenAPermanentIsPutIntoAPlayersGraveyard":                         ["t:enters_graveyard"],
    "WhenACardIsPutIntoAPlayersGraveyardFromAnywhere":                  ["t:enters_graveyard"],
    "WhenAnyNumberOfGraveyardCardsLeave":                               ["t:graveyard_leave"],
    "WhenAPermanentIsTurnedFaceUp":                                     ["t:turned_face_up"],
    # Combat — attacks
    "WhenACreatureAttacks":                                             ["t:attacks"],
    "WhenACreatureAttacksAlone":                                        ["t:attacks"],
    "WhenACreatureAttacksAPlayer":                                      ["t:attacks"],
    "WhenACreatureAttacksAndIsntBlocked":                               ["t:attacks"],
    "WhenAPlayerAttacks":                                               ["t:attacks"],
    "WhenAnyNumberOfCreaturesAttack":                                   ["t:attacks"],
    "WhenAPlayerAttacksWithAnyNumberOfCreatures":                       ["t:attacks"],
    # Combat — blocks / damage
    "WhenACreatureBlocksACreature":                                     ["t:blocks"],
    "WhenACreatureBlocks":                                              ["t:blocks"],
    "WhenACreatureBecomesBlocked":                                      ["t:blocked"],
    "WhenACreatureBecomesBlockedByACreature":                           ["t:blocked"],
    "WhenACreatureDealsCombatDamage":                                   ["t:combat_damage"],
    "WhenACreatureDealsCombatDamageToAPlayer":                          ["t:combat_damage"],
    "WhenAnyNumberOfCreaturesDealCombatDamageToAPlayer":                ["t:combat_damage"],
    "WhenACreatureDealsCombatDamageToAPermanent":                       ["t:combat_damage"],
    # Damage
    "WhenAPermanentDealsAnAmountOfDamage":                              ["t:damage_dealt"],
    "WhenASourceDealsDamageToAPlayer":                                  ["t:damage_dealt"],
    "WhenASourceDealsDamageToACreature":                                ["t:damage_dealt"],
    "WhenAPermanentIsDealDamage":                                       ["t:damage_dealt"],
    "WhenAPermanentDealsDamage":                                        ["t:damage_dealt"],
    "WhenAPermanentDealsDamageToAPlayer":                               ["t:damage_dealt"],
    "WhenAPermanentIsDealtDamage":                                      ["t:damage_dealt"],
    # Player actions
    "WhenAPlayerDrawsACard":                                            ["t:draw"],
    "WhenAPlayerDrawsTheirNthCardEachTurn":                             ["t:draw"],
    "WhenAPlayerDiscardsACard":                                         ["t:discard"],
    "WhenAPlayerCastsASpell":                                           ["t:cast_spell"],
    "WhenAPlayerCastsANonCreatureSpell":                                ["t:cast_spell"],
    "WhenAPlayerCastsACreatureSpell":                                   ["t:cast_spell"],
    "WhenAPlayerCastsTheirNthSpellInATurn":                             ["t:cast_spell"],
    "WhenAPlayerActivatesAnAbility":                                    ["t:activated_ability"],
    "WhenAPlayerGainsLife":                                             ["t:life_gained"],
    "WhenAPlayerLosesLife":                                             ["t:life_lost"],
    "WhenAPlayerTapsAPermanent":                                        ["t:tap"],
    "WhenAPlayerTapsAPermanentForMana":                                 ["t:mana_tapped"],
    "WhenAPlayerProliferates":                                          ["t:proliferate_trigger"],
    "WhenAPlayerCyclesACard":                                           ["t:cycle"],
    "WhenAPlayerCopiesASpell":                                          ["t:cast_spell"],
    # Counters
    "WhenACounterOfTypeIsPutOnAPermanent":                              ["t:counter_placed"],
    "WhenACounterOfTypeIsRemovedFromAPermanent":                        ["t:counter_removed"],
    "WhenACounterIsPutOnAPermanent":                                    ["t:counter_placed"],
    "WhenTheLastCounterOfTypeIsRemovedFromAPermanent":                  ["t:counter_removed"],
    # Tapping/untapping
    "WhenAPermanentBecomesTapped":                                      ["t:tapped"],
    "WhenAPermanentBecomesUntapped":                                    ["t:untap"],
    # Targeting
    "WhenAPermanentBecomesTheTargetOfASpellOrAbility":                  ["t:targeted"],
    # Phase / step
    "AtTheBeginningOfAPlayersUpkeep":                                   ["t:upkeep"],
    "AtTheBeginningOfAPlayersDrawStep":                                 ["t:draw_step"],
    "AtTheBeginningOfAPlayersMainPhases":                               ["t:main_phase"],
    "AtTheBeginningOfAPlayersFirstMainPhase":                           ["t:main_phase"],
    "AtTheBeginningOfCombat":                                           ["t:combat"],
    "AtTheBeginningOfCombatDuringAPlayersTurn":                         ["t:combat"],
    "AtTheEndOfCombat":                                                 ["t:end_of_combat"],
    "AtTheBeginningOfAPlayersEndStep":                                  ["t:end_step"],
    "AtTheBeginningOfEachEndStep":                                      ["t:end_step"],
    # Tokens / special
    "WhenATokenEntersTheBattlefield":                                   ["t:token_created"],
    "WhenATokenIsCreated":                                              ["t:token_created"],
    "WhenACreatureMutates":                                             ["t:mutate"],
    "WhenACreatureSpecializes":                                         ["t:specialize"],
    "WhenAPlayerCompletesADungeon":                                     ["t:venture"],
    "WhenAPlayerSolvesACase":                                           ["t:case_solved"],
    "WhenSpellOrAbilityManaSourceIsActivated":                          ["t:mana_ability"],
}

# ── Action map ────────────────────────────────────────────────────────────────

ACTION_MAP: dict[str, list[str]] = {
    # Card draw / hand
    "DrawACard":                                 ["e:draw"],
    "DrawNumberCards":                           ["e:draw"],
    "DrawUntilHandSize":                         ["e:draw"],
    "DrawACardForEach":                          ["e:draw"],
    "LookAtTheTopNumberCardsOfLibrary":          ["e:scry"],
    "LookAtTopCards":                            ["e:scry"],
    "Surveil":                                   ["e:surveil"],
    "Scry":                                      ["e:scry"],
    "DiscardACard":                              ["e:discard"],
    "DiscardNumberCards":                        ["e:discard"],
    "DiscardHandAndDraw":                        ["e:discard", "e:draw"],
    "DiscardACardAtRandom":                      ["e:discard"],
    "DiscardCardForEach":                        ["e:discard"],
    # Damage
    "DealsDamage":                               ["e:damage"],
    "DealsDamageToAny":                          ["e:damage"],
    "DealsDamageToCreature":                     ["e:damage"],
    "DealsDamageToPlayer":                       ["e:damage"],
    "DeadPermanentDealsDamage":                  ["e:damage"],
    "PermanentDealsDamage":                      ["e:damage"],
    "PermanentDealsDamageForEach":               ["e:damage"],
    "SpellDealsDamage":                          ["e:damage"],
    "SpellDealsDamageToAny":                     ["e:damage"],
    "SpellDealsDamageForEach":                   ["e:damage"],
    "SourceDealsDamage":                         ["e:damage"],
    "DealsDamageEqualToX":                       ["e:damage"],
    # Life
    "GainLife":                                  ["e:gain_life"],
    "GainLifeForEach":                           ["e:gain_life"],
    "GainLifeEqualToDamage":                     ["e:gain_life"],
    "LoseLife":                                  ["e:lose_life"],
    "LoseLifeForEach":                           ["e:lose_life"],
    "EachOpponentLosesLife":                     ["e:lose_life"],
    "ExchangeLifeTotalWithPlayer":               ["e:gain_life", "e:lose_life"],
    # Destroy / exile
    "DestroyPermanent":                          ["e:destroy"],
    "DestroyAllPermanents":                      ["e:destroy", "e:board_wipe"],
    "DestroyEachPermanent":                      ["e:destroy", "e:board_wipe"],
    "DestroyAllCreatures":                       ["e:destroy", "e:board_wipe"],
    "ExileACard":                                ["e:exile"],
    "ExilePermanent":                            ["e:exile"],
    "ExileAllCreatures":                         ["e:exile", "e:board_wipe"],
    "ExileGraveyardCard":                        ["e:exile"],
    "ExileGraveyard":                            ["e:exile"],
    "SacrificePermanent":                        ["e:sacrifice"],
    "SacrificeAPermanent":                       ["e:sacrifice"],
    "SacrificeNumberPermanents":                 ["e:sacrifice"],
    # Counters
    "PutACounterOfTypeOnPermanent":              ["e:add_counter"],
    "PutNumberCountersOfTypeOnPermanent":        ["e:add_counter"],
    "PutCountersOnEach":                         ["e:add_counter"],
    "PutACounterOfTypeOnEachPermanent":          ["e:add_counter", "e:proliferate"],
    "RemoveACounterOfTypeFromPermanent":         ["e:remove_counter"],
    "RemoveNumberCountersOfTypeFromPermanent":   ["e:remove_counter"],
    "MoveACounterOfTypeFromPermanentOntoAnotherPermanent": ["e:remove_counter", "e:add_counter"],
    "DoubleCountersOfTypeOnPermanent":           ["e:add_counter"],
    "Proliferate":                               ["e:proliferate"],
    # Tokens
    "CreateTokens":                              ["e:create_token"],
    "CreateTokensWithFlags":                     ["e:create_token"],
    "CreateNumberTokens":                        ["e:create_token"],
    "ForEachPlayerCreateTokens":                 ["e:create_token"],
    "PopulateNumberTimes":                       ["e:populate"],
    "Populate":                                  ["e:populate"],
    # Library / tutoring
    "SearchLibrary":                             ["e:tutor"],
    "SearchLibraryAndGraveyard":                 ["e:tutor"],
    "SeekACard":                                 ["e:tutor"],
    "LookAtTopCardsAndPutSomeInHand":            ["e:tutor"],
    # Mill
    "MillACard":                                 ["e:mill"],
    "MillNumberCards":                           ["e:mill"],
    "MillUntilCondition":                        ["e:mill"],
    # Graveyard recursion / reanimate
    "ReturnACardFromGraveyard":                  ["e:reanimate"],
    "ReturnPermanentFromGraveyard":              ["e:reanimate"],
    "CastGraveyardCardWithoutPaying":            ["e:reanimate"],
    "PutGraveyardCardOntoBattlefield":           ["e:reanimate"],
    "PutGraveyardCardIntoHand":                  ["e:reanimate"],
    "PutGraveyardCardOnTopOfLibrary":            ["e:reanimate"],
    # Return to hand (bounce)
    "ReturnToHand":                              ["e:bounce"],
    "ReturnPermanentToHand":                     ["e:bounce"],
    "PutPermanentIntoItsOwnersHand":             ["e:bounce"],
    # Tap / untap
    "TapPermanent":                              ["e:tap"],
    "TapNumberPermanents":                       ["e:tap"],
    "UntapPermanent":                            ["e:untap"],
    "UntapAllPermanents":                        ["e:untap"],
    "UntapEachPermanent":                        ["e:untap"],
    # Counter spells
    "CounterSpell":                              ["e:counter_spell"],
    "CounterSpellUnless":                        ["e:counter_spell"],
    # Copy
    "CopySpell":                                 ["e:copy"],
    "CopyPermanent":                             ["e:copy"],
    "CopyATrigger":                              ["e:copy"],
    # Transform / phase
    "TransformPermanent":                        ["e:transform"],
    "PhaseOutPermanent":                         ["e:phase_out"],
    # Mana
    "AddMana":                                   ["e:mana"],
    "AddManaWithModifiers":                      ["e:mana"],
    "AddManaRepeated":                           ["e:mana"],
    # Pump / buff (layer effects — also recurse into args for keywords)
    "CreatePermanentLayerEffectUntil":           ["e:pump"],
    "CreateEachPermanentLayerEffectUntil":       ["e:pump"],
    "CreatePermanentRuleEffectUntil":            ["e:pump"],
    "CreatePermanentLayerEffect":                ["e:pump"],
    "ModifyPT":                                  ["e:pump"],
    # Discover / explore / venture / investigate
    "Discover":                                  ["e:discover"],
    "Explore":                                   ["e:explore"],
    "VentureIntoTheDungeon":                     ["e:venture"],
    "Investigate":                               ["e:investigate"],
    # Special
    "BecomeTheMonarch":                          ["e:monarch"],
    "TakeTheInitiative":                         ["e:initiative"],
    "FightCreatures":                            ["e:fight"],
    "HaveCreaturesFight":                        ["e:fight"],
    "GainControl":                               ["e:steal"],
    "GainControlOfPermanent":                    ["e:steal"],
    "AttachAPermanentToAPermanent":              ["e:equip"],
    "FlipACoin":                                 ["e:flip_coin"],
    "RollAD6":                                   ["e:roll_dice"],
    "RollAD20":                                  ["e:roll_dice"],
    "EndTheTurn":                                ["e:end_turn"],
    "TakeExtraTurn":                             ["e:extra_turn"],
    "RegeneratePermanent":                       ["e:regenerate"],
    "ReflexiveTrigger":                          [],  # structural wrapper, handled by recursion
}

# ── Permanent cardtype map (_Permanents: "IsCardtype" → perm: tags) ───────────
# Captures WHAT TYPE of permanent the ability cares about.

PERMANENT_CARDTYPE_MAP: dict[str, list[str]] = {
    "Creature":     ["perm:creature"],
    "Artifact":     ["perm:artifact"],
    "Land":         ["perm:land"],
    "Enchantment":  ["perm:enchantment"],
    "Planeswalker": ["perm:planeswalker"],
    "Battle":       ["perm:battle"],
    "Instant":      ["perm:instant"],
    "Sorcery":      ["perm:sorcery"],
}

# ── Counter type map ──────────────────────────────────────────────────────────

COUNTER_MAP: dict[str, list[str]] = {
    "PoisonCounter":       ["c:poison"],
    "LoyaltyCounter":      ["c:loyalty"],
    "ExperienceCounter":   ["c:experience"],
    "ChargeCounter":       ["c:charge"],
    "OilCounter":          ["c:oil"],
    "TimeCounter":         ["c:time"],
    "StorageCounter":      ["c:storage"],
    "BloodCounter":        ["c:blood"],
    "BlightCounter":       ["c:blight"],
    "AimCounter":          ["c:aim"],
    "AgeCounter":          ["c:age"],
    "FadeCounter":         ["c:fade"],
    "GrowthCounter":       ["c:growth"],
    "QuestCounter":        ["c:quest"],
    "LoreCounter":         ["c:lore"],
    "DoomCounter":         ["c:doom"],
    "WishCounter":         ["c:wish"],
    "SleepCounter":        ["c:sleep"],
    "SporeCounter":        ["c:spore"],
    "HungerCounter":       ["c:hunger"],
    "ShieldCounter":       ["c:shield"],
    "IceCounter":          ["c:ice"],
    "EggCounter":          ["c:egg"],
    "HatchingCounter":     ["c:hatching"],
    "LevelCounter":        ["c:level"],
    "PageCounter":         ["c:page"],
    "TaskCounter":         ["c:task"],
}

# ── Keyword rules map ─────────────────────────────────────────────────────────

KEYWORD_MAP: dict[str, list[str]] = {
    "Flying":           ["k:flying"],
    "Trample":          ["k:trample"],
    "Deathtouch":       ["k:deathtouch"],
    "Lifelink":         ["k:lifelink"],
    "Menace":           ["k:menace"],
    "Vigilance":        ["k:vigilance"],
    "Haste":            ["k:haste"],
    "FirstStrike":      ["k:first_strike"],
    "First Strike":     ["k:first_strike"],
    "DoubleStrike":     ["k:double_strike"],
    "Double Strike":    ["k:double_strike"],
    "Hexproof":         ["k:hexproof"],
    "Indestructible":   ["k:indestructible"],
    "Shroud":           ["k:shroud"],
    "Protection":       ["k:protection"],
    "Reach":            ["k:reach"],
    "Flash":            ["k:flash"],
    "Ward":             ["k:ward"],
    "Infect":           ["k:infect"],
    "Wither":           ["k:wither"],
    "Toxic":            ["k:toxic"],
    "Proliferate":      ["k:proliferate", "e:proliferate"],
    "Convoke":          ["k:convoke"],
    "Delve":            ["k:delve"],
    "Flashback":        ["k:flashback"],
    "Equip":            ["k:equip"],
    "Cycling":          ["k:cycling"],
    "Kicker":           ["k:kicker"],
    "Multikicker":      ["k:kicker"],
    "Replicate":        ["k:replicate"],
    "Echo":             ["k:echo"],
    "Persist":          ["k:persist"],
    "Undying":          ["k:undying"],
    "Modular":          ["k:modular"],
    "Graft":            ["k:graft"],
    "Evolve":           ["k:evolve"],
    "Exploit":          ["k:exploit"],
    "Extort":           ["k:extort"],
    "Prowess":          ["k:prowess"],
    "Mentor":           ["k:mentor"],
    "Mutate":           ["k:mutate"],
    "Escape":           ["k:escape"],
    "Foretell":         ["k:foretell"],
    "Backup":           ["k:backup"],
    "Blitz":            ["k:blitz"],
    "Disturb":          ["k:disturb"],
    "Cleave":           ["k:cleave"],
    "Reconfigure":      ["k:reconfigure"],
    "Training":         ["k:training"],
    "Ninjutsu":         ["k:ninjutsu"],
    "Dredge":           ["k:dredge"],
    "Storm":            ["k:storm"],
    "Cascade":          ["k:cascade"],
    "Suspend":          ["k:suspend"],
    "Madness":          ["k:madness"],
    "Channel":          ["k:channel"],
    "Landfall":         ["k:landfall", "t:landfall"],
    "Transmute":        ["k:transmute"],
    "Unearth":          ["k:unearth"],
    "Scavenge":         ["k:scavenge"],
    "Outlast":          ["k:outlast"],
    "Fabricate":        ["k:fabricate"],
    "Enlist":           ["k:enlist"],
    "Investigate":      ["k:investigate", "e:investigate"],
    "Connive":          ["k:connive"],
    "Squad":            ["k:squad"],
    "Discover":         ["k:discover", "e:discover"],
    "Explore":          ["k:explore", "e:explore"],
    "Collect Evidence": ["k:collect_evidence"],
    "Offspring":        ["k:offspring"],
    "Impending":        ["k:impending"],
    "Gift":             ["k:gift"],
}

# ── Replacement rule map ──────────────────────────────────────────────────────

REPLACEMENT_MAP: dict[str, list[str]] = {
    "ReplaceWouldDraw":             ["r:replace_draw"],
    "ReplaceWouldDealDamage":       ["r:replace_damage"],
    "ReplaceWouldEnter":            ["r:replace_etb"],
    "ReplaceWouldLeaveTheBattlefield": ["r:replace_death"],
    "ReplaceWouldDestroy":          ["r:replace_destroy"],
    "ReplaceWouldDiscard":          ["r:replace_discard"],
    "ReplaceWouldMill":             ["r:replace_mill"],
    "ReplaceWouldPutCounters":      ["r:replace_counters"],
    "ReplaceWouldPutIntoGraveyard": ["r:replace_death"],
    "ReplaceWouldGainLife":         ["r:replace_lifegain"],
    "ReplaceWouldLoseLife":         ["r:replace_lifeloss"],
}

# ── Player/targeting map ──────────────────────────────────────────────────────

PLAYER_MAP: dict[str, list[str]] = {
    "You":                  ["tgt:self"],
    "ActivePlayer":         ["tgt:self"],
    "Controller":           ["tgt:self"],
    "Owner":                ["tgt:self"],
    "EachOpponent":         ["tgt:opponent"],
    "OpponentsController":  ["tgt:opponent"],
    "ChooseOpponent":       ["tgt:opponent"],
    "AffectedPlayer":       ["tgt:opponent"],
    "AnyPlayer":            ["tgt:any_player"],
    "ChooseAPlayer":        ["tgt:any_player"],
    "EachPlayer":           ["tgt:each_player"],
}

PLAYERS_MAP: dict[str, list[str]] = {
    "AllOpponents":   ["tgt:opponent"],
    "AllPlayers":     ["tgt:each_player"],
    "SingleOpponent": ["tgt:opponent"],
    "SinglePlayer":   [],  # context-dependent — don't tag
}

# ── Display metadata ──────────────────────────────────────────────────────────

TAG_META: dict[str, dict] = {
    # Perm Types
    "perm:creature":     {"label": "creature",      "group": "Perm Types", "color": "#22c55e"},
    "perm:artifact":     {"label": "artifact",      "group": "Perm Types", "color": "#9aa0a6"},
    "perm:enchantment":  {"label": "enchantment",   "group": "Perm Types", "color": "#a855f7"},
    "perm:land":         {"label": "land",           "group": "Perm Types", "color": "#c9a227"},
    "perm:planeswalker": {"label": "planeswalker",   "group": "Perm Types", "color": "#3b82f6"},
    "perm:battle":       {"label": "battle",         "group": "Perm Types", "color": "#f97316"},
    "perm:instant":      {"label": "instant",        "group": "Perm Types", "color": "#3b82f6"},
    "perm:sorcery":      {"label": "sorcery",        "group": "Perm Types", "color": "#f97316"},
    "perm:token":        {"label": "token",          "group": "Perm Types", "color": "#22c55e"},
    # Triggers
    "t:etb":                {"label": "enters battlefield",  "group": "Triggers", "color": "#ef4444"},
    "t:creature_dies":      {"label": "creature dies",       "group": "Triggers", "color": "#ef4444"},
    "t:leaves":             {"label": "leaves battlefield",  "group": "Triggers", "color": "#ef4444"},
    "t:permanent_destroyed":{"label": "permanent destroyed", "group": "Triggers", "color": "#ef4444"},
    "t:enters_graveyard":   {"label": "enters graveyard",   "group": "Triggers", "color": "#ef4444"},
    "t:attacks":            {"label": "attacks",             "group": "Triggers", "color": "#ef4444"},
    "t:blocks":             {"label": "blocks",              "group": "Triggers", "color": "#ef4444"},
    "t:blocked":            {"label": "becomes blocked",     "group": "Triggers", "color": "#ef4444"},
    "t:combat_damage":      {"label": "deals combat damage", "group": "Triggers", "color": "#ef4444"},
    "t:damage_dealt":       {"label": "damage dealt",        "group": "Triggers", "color": "#ef4444"},
    "t:draw":               {"label": "card drawn",          "group": "Triggers", "color": "#ef4444"},
    "t:discard":            {"label": "card discarded",      "group": "Triggers", "color": "#ef4444"},
    "t:cast_spell":         {"label": "spell cast",          "group": "Triggers", "color": "#ef4444"},
    "t:counter_placed":     {"label": "counter placed",      "group": "Triggers", "color": "#ef4444"},
    "t:counter_removed":    {"label": "counter removed",     "group": "Triggers", "color": "#ef4444"},
    "t:sacrifice":          {"label": "sacrificed",          "group": "Triggers", "color": "#ef4444"},
    "t:life_gained":        {"label": "life gained",         "group": "Triggers", "color": "#ef4444"},
    "t:life_lost":          {"label": "life lost",           "group": "Triggers", "color": "#ef4444"},
    "t:exiled":             {"label": "permanent exiled",    "group": "Triggers", "color": "#ef4444"},
    "t:tapped":             {"label": "permanent tapped",    "group": "Triggers", "color": "#ef4444"},
    "t:untap":              {"label": "untaps",              "group": "Triggers", "color": "#ef4444"},
    "t:targeted":           {"label": "targeted",            "group": "Triggers", "color": "#ef4444"},
    "t:cycle":              {"label": "cycling",             "group": "Triggers", "color": "#ef4444"},
    "t:upkeep":             {"label": "upkeep",              "group": "Triggers", "color": "#ef4444"},
    "t:end_step":           {"label": "end step",            "group": "Triggers", "color": "#ef4444"},
    "t:combat":             {"label": "begin combat",        "group": "Triggers", "color": "#ef4444"},
    "t:end_of_combat":      {"label": "end of combat",       "group": "Triggers", "color": "#ef4444"},
    "t:main_phase":         {"label": "main phase",          "group": "Triggers", "color": "#ef4444"},
    "t:token_created":      {"label": "token created",       "group": "Triggers", "color": "#ef4444"},
    "t:landfall":           {"label": "land enters",         "group": "Triggers", "color": "#ef4444"},
    "t:activated_ability":  {"label": "ability activated",   "group": "Triggers", "color": "#ef4444"},
    "t:proliferate_trigger":{"label": "proliferate trigger", "group": "Triggers", "color": "#ef4444"},
    "t:transform":          {"label": "transforms",          "group": "Triggers", "color": "#ef4444"},
    "t:mana_tapped":        {"label": "tapped for mana",     "group": "Triggers", "color": "#ef4444"},
    "t:mana_ability":       {"label": "mana ability",        "group": "Triggers", "color": "#ef4444"},
    "t:mutate":             {"label": "mutates",             "group": "Triggers", "color": "#ef4444"},
    "t:graveyard_leave":    {"label": "leaves graveyard",    "group": "Triggers", "color": "#ef4444"},
    "t:turned_face_up":     {"label": "turned face up",      "group": "Triggers", "color": "#ef4444"},
    # Effects
    "e:draw":           {"label": "draw cards",      "group": "Effects", "color": "#3b82f6"},
    "e:discard":        {"label": "discard",         "group": "Effects", "color": "#3b82f6"},
    "e:damage":         {"label": "deal damage",     "group": "Effects", "color": "#f97316"},
    "e:gain_life":      {"label": "gain life",       "group": "Effects", "color": "#22c55e"},
    "e:lose_life":      {"label": "lose life",       "group": "Effects", "color": "#f97316"},
    "e:destroy":        {"label": "destroy",         "group": "Effects", "color": "#a855f7"},
    "e:exile":          {"label": "exile",           "group": "Effects", "color": "#a855f7"},
    "e:bounce":         {"label": "return to hand",  "group": "Effects", "color": "#3b82f6"},
    "e:board_wipe":     {"label": "board wipe",      "group": "Effects", "color": "#a855f7"},
    "e:sacrifice":      {"label": "sacrifice",       "group": "Effects", "color": "#a855f7"},
    "e:create_token":   {"label": "create tokens",   "group": "Effects", "color": "#22c55e"},
    "e:populate":       {"label": "populate",        "group": "Effects", "color": "#22c55e"},
    "e:add_counter":    {"label": "put counters",    "group": "Effects", "color": "#c9a227"},
    "e:remove_counter": {"label": "remove counters", "group": "Effects", "color": "#c9a227"},
    "e:proliferate":    {"label": "proliferate",     "group": "Effects", "color": "#c9a227"},
    "e:tutor":          {"label": "search library",  "group": "Effects", "color": "#3b82f6"},
    "e:mill":           {"label": "mill",            "group": "Effects", "color": "#9aa0a6"},
    "e:reanimate":      {"label": "reanimate",       "group": "Effects", "color": "#a855f7"},
    "e:surveil":        {"label": "surveil",         "group": "Effects", "color": "#3b82f6"},
    "e:scry":           {"label": "scry",            "group": "Effects", "color": "#3b82f6"},
    "e:counter_spell":  {"label": "counter spell",   "group": "Effects", "color": "#3b82f6"},
    "e:fight":          {"label": "fight",           "group": "Effects", "color": "#f97316"},
    "e:tap":            {"label": "tap",             "group": "Effects", "color": "#9aa0a6"},
    "e:untap":          {"label": "untap",           "group": "Effects", "color": "#9aa0a6"},
    "e:transform":      {"label": "transform",       "group": "Effects", "color": "#c9a227"},
    "e:copy":           {"label": "copy",            "group": "Effects", "color": "#a855f7"},
    "e:steal":          {"label": "steal control",   "group": "Effects", "color": "#a855f7"},
    "e:mana":           {"label": "add mana",        "group": "Effects", "color": "#22c55e"},
    "e:extra_turn":     {"label": "extra turn",      "group": "Effects", "color": "#c9a227"},
    "e:pump":           {"label": "pump/buff",       "group": "Effects", "color": "#c9a227"},
    "e:investigate":    {"label": "investigate",     "group": "Effects", "color": "#c9a227"},
    "e:discover":       {"label": "discover",        "group": "Effects", "color": "#c9a227"},
    "e:explore":        {"label": "explore",         "group": "Effects", "color": "#22c55e"},
    "e:venture":        {"label": "venture",         "group": "Effects", "color": "#c9a227"},
    "e:monarch":        {"label": "the monarch",     "group": "Effects", "color": "#c9a227"},
    "e:phase_out":      {"label": "phase out",       "group": "Effects", "color": "#9aa0a6"},
    "e:regenerate":     {"label": "regenerate",      "group": "Effects", "color": "#22c55e"},
    "e:flip_coin":      {"label": "flip coin",       "group": "Effects", "color": "#9aa0a6"},
    "e:roll_dice":      {"label": "roll dice",       "group": "Effects", "color": "#9aa0a6"},
    "e:equip":          {"label": "equip",           "group": "Effects", "color": "#9aa0a6"},
    # Counters
    "c:plus1":     {"label": "+1/+1 counter",  "group": "Counters", "color": "#22c55e"},
    "c:minus1":    {"label": "-1/-1 counter",  "group": "Counters", "color": "#ef4444"},
    "c:poison":    {"label": "poison",         "group": "Counters", "color": "#a855f7"},
    "c:loyalty":   {"label": "loyalty",        "group": "Counters", "color": "#3b82f6"},
    "c:experience":{"label": "experience",     "group": "Counters", "color": "#c9a227"},
    "c:charge":    {"label": "charge",         "group": "Counters", "color": "#9aa0a6"},
    "c:oil":       {"label": "oil",            "group": "Counters", "color": "#9aa0a6"},
    "c:time":      {"label": "time",           "group": "Counters", "color": "#c9a227"},
    "c:blight":    {"label": "blight",         "group": "Counters", "color": "#a855f7"},
    "c:shield":    {"label": "shield",         "group": "Counters", "color": "#22c55e"},
    "c:lore":      {"label": "lore",           "group": "Counters", "color": "#c9a227"},
    "c:storage":   {"label": "storage",        "group": "Counters", "color": "#9aa0a6"},
    "c:quest":     {"label": "quest",          "group": "Counters", "color": "#c9a227"},
    "c:blood":     {"label": "blood",          "group": "Counters", "color": "#ef4444"},
    # Keywords
    "k:flying":        {"label": "flying",        "group": "Keywords", "color": "#7c5cff"},
    "k:trample":       {"label": "trample",       "group": "Keywords", "color": "#7c5cff"},
    "k:deathtouch":    {"label": "deathtouch",    "group": "Keywords", "color": "#7c5cff"},
    "k:lifelink":      {"label": "lifelink",      "group": "Keywords", "color": "#7c5cff"},
    "k:menace":        {"label": "menace",        "group": "Keywords", "color": "#7c5cff"},
    "k:vigilance":     {"label": "vigilance",     "group": "Keywords", "color": "#7c5cff"},
    "k:haste":         {"label": "haste",         "group": "Keywords", "color": "#7c5cff"},
    "k:first_strike":  {"label": "first strike",  "group": "Keywords", "color": "#7c5cff"},
    "k:double_strike": {"label": "double strike", "group": "Keywords", "color": "#7c5cff"},
    "k:hexproof":      {"label": "hexproof",      "group": "Keywords", "color": "#7c5cff"},
    "k:indestructible":{"label": "indestructible","group": "Keywords", "color": "#7c5cff"},
    "k:ward":          {"label": "ward",          "group": "Keywords", "color": "#7c5cff"},
    "k:infect":        {"label": "infect",        "group": "Keywords", "color": "#7c5cff"},
    "k:wither":        {"label": "wither",        "group": "Keywords", "color": "#7c5cff"},
    "k:toxic":         {"label": "toxic",         "group": "Keywords", "color": "#7c5cff"},
    "k:proliferate":   {"label": "proliferate",   "group": "Keywords", "color": "#7c5cff"},
    "k:flash":         {"label": "flash",         "group": "Keywords", "color": "#7c5cff"},
    "k:reach":         {"label": "reach",         "group": "Keywords", "color": "#7c5cff"},
    "k:convoke":       {"label": "convoke",       "group": "Keywords", "color": "#7c5cff"},
    "k:delve":         {"label": "delve",         "group": "Keywords", "color": "#7c5cff"},
    "k:flashback":     {"label": "flashback",     "group": "Keywords", "color": "#7c5cff"},
    "k:equip":         {"label": "equip",         "group": "Keywords", "color": "#7c5cff"},
    "k:cycling":       {"label": "cycling",       "group": "Keywords", "color": "#7c5cff"},
    "k:kicker":        {"label": "kicker",        "group": "Keywords", "color": "#7c5cff"},
    "k:persist":       {"label": "persist",       "group": "Keywords", "color": "#7c5cff"},
    "k:undying":       {"label": "undying",       "group": "Keywords", "color": "#7c5cff"},
    "k:modular":       {"label": "modular",       "group": "Keywords", "color": "#7c5cff"},
    "k:graft":         {"label": "graft",         "group": "Keywords", "color": "#7c5cff"},
    "k:evolve":        {"label": "evolve",        "group": "Keywords", "color": "#7c5cff"},
    "k:extort":        {"label": "extort",        "group": "Keywords", "color": "#7c5cff"},
    "k:prowess":       {"label": "prowess",       "group": "Keywords", "color": "#7c5cff"},
    "k:mutate":        {"label": "mutate",        "group": "Keywords", "color": "#7c5cff"},
    "k:escape":        {"label": "escape",        "group": "Keywords", "color": "#7c5cff"},
    "k:cascade":       {"label": "cascade",       "group": "Keywords", "color": "#7c5cff"},
    "k:storm":         {"label": "storm",         "group": "Keywords", "color": "#7c5cff"},
    "k:suspend":       {"label": "suspend",       "group": "Keywords", "color": "#7c5cff"},
    "k:dredge":        {"label": "dredge",        "group": "Keywords", "color": "#7c5cff"},
    "k:madness":       {"label": "madness",       "group": "Keywords", "color": "#7c5cff"},
    "k:landfall":      {"label": "landfall",      "group": "Keywords", "color": "#7c5cff"},
    "k:ninjutsu":      {"label": "ninjutsu",      "group": "Keywords", "color": "#7c5cff"},
    "k:discover":      {"label": "discover",      "group": "Keywords", "color": "#7c5cff"},
    "k:explore":       {"label": "explore",       "group": "Keywords", "color": "#7c5cff"},
    "k:connive":       {"label": "connive",       "group": "Keywords", "color": "#7c5cff"},
    "k:investigate":   {"label": "investigate",   "group": "Keywords", "color": "#7c5cff"},
    # Targets
    "tgt:self":        {"label": "targets self",     "group": "Targets", "color": "#9aa0a6"},
    "tgt:opponent":    {"label": "targets opponent", "group": "Targets", "color": "#ef4444"},
    "tgt:any_player":  {"label": "any player",       "group": "Targets", "color": "#9aa0a6"},
    "tgt:each_player": {"label": "each player",      "group": "Targets", "color": "#9aa0a6"},
    # Replacement
    "r:replace_draw":     {"label": "replaces draws",     "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_death":    {"label": "replaces death",     "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_damage":   {"label": "redirects damage",   "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_etb":      {"label": "enters differently", "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_counters": {"label": "modifies counters",  "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_mill":     {"label": "replaces mill",      "group": "Replacement", "color": "#9aa0a6"},
    "r:replace_discard":  {"label": "replaces discard",   "group": "Replacement", "color": "#9aa0a6"},
}

TAG_GROUPS = ["Perm Types", "Triggers", "Effects", "Counters", "Keywords", "Targets", "Replacement"]
